export const SHORT_FILM_DURATION = 40;
export const LARGE_WIDTH_MOVIES_DISPLAY = 12;
export const MEDIUM_WIDTH_MOVIES_DISPLAY = 8;
export const SMALL_WIDTH_MOVIES_DISPLAY = 5;
export const CONFLICT_ERROR_STATUS_CODE = 409;
export const UNAUTHORIZED_ERROR_STATUS_CODE = 401;
